name = "paulimerFormal"
version = "0.1.0"
keywords = ["formal-verification", "quantum-computing"]
defaultTargets = ["PaulimerFormal"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
maxSynthPendingDepth = 3
warningAsError = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.2"

[[lean_lib]]
name = "PaulimerFormal"
